---
title: "Urban Heat Island Visual Correlations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, include = FALSE, comment=" "}
library(tidyverse)
library(sf)
library(leaflet)
library(tmap)
library(spatstat)
library(maptools)
library(sp)
library(raster)
#library(beepr)
library(RColorBrewer)
library(stargazer)

```

```{r, include = FALSE}
tree_prioritization <- st_read(dsn = ".", layer = "geo_export_2e82f388-c013-45a0-bb25-522154013165") %>% 
   st_transform(crs = 4326)

tree_map = raster("tree_canopy_2010.tif") 

Wallercreek <- st_read(dsn = ".", layer = "WallerCrk") %>% 
   st_transform(crs = 4326) 

Wallercensus <- st_read(dsn = ".", layer = "wallercensus") %>% 
   st_transform(crs = 4326) 
```


```{r, include=FALSE}
#plot(tree_map)

tree_prioritization_uhi = tree_prioritization %>% 
  dplyr::select(uhi) %>% 
  mutate(Intensity = uhi)

#%>% 
  #mutate(census_id = 1:200) %>% 
  #mutate(treecount = freq)
#tree_prior_r =raster(tree_prioritization_uhi, vals = tree_prioritization$uhi)

#beep(3)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
#tmap_mode("view")
#tm_basemap("Esri.WorldStreetMap")+
#  tm_shape(tree_prioritization_uhi)+
# tm_fill("Intensity", low = "oldlace", high = "red4", alpha = 0.6)+
# tm_legend(title ="Relative Urban Heat Island Intensity by Census Tract")
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
air_palette = c("orchid4","cornflowerblue")

tmap_mode("view")
tm_basemap("Esri.WorldImagery")+
  tm_shape(tree_prioritization_uhi)+
  tm_fill("Intensity", low = "oldlace", high = "red4", alpha = 0.7)+
  tm_legend(title ="Relative Urban Heat Island Intensity by Census Tract")+
  tm_shape(Wallercreek)+
  tm_borders(col = "black", lwd = 1)#+
  #tm_shape(tree_prioritization)+
  #tm_fill("air_qual", palette = air_palette, alpha = 0.7)
 
 # tm_shape(tree_map_shape)#+
  #tm_dots("DN", palette = "darkgreen")
```

```{r, include=FALSE}
#leaflet(tree_prioritization_uhi) %>% #need to change the coordinate reference system to match
 # addPolygons()


uhi_plot = ggplot(tree_prioritization_uhi)+
  geom_sf(aes(fill = uhi))+
  scale_fill_gradient("Comparitive Intensity", low = "oldlace", high = "red4")+
  
  labs(x = "", y = "", title = "Comparitive Urban Heat Island of Census \nTracts Based off Land Surface Temperature")+
  geom_sf(data = Wallercreek, 
          fill = "NA", 
          color = "black", 
          size = 1)+
  theme_minimal()+
  coord_sf(datum=NA)

uhi_plot
```
```{r, include=FALSE}

mapRange <- c(range(st_coordinates(Wallercreek)[,1]),range(st_coordinates(Wallercreek)[,2]))

uhi_plot_waller = ggplot(tree_prioritization_uhi)+
  geom_sf(aes(fill = uhi))+
  scale_fill_gradient("Comparitive Intensity", low = "oldlace", high = "red4")+
  #coord_sf(xlim = mapRange[c(1:2)], ylim = mapRange[c(3:4)])+
  labs(x = "", y = "", title = "Comparitive Urban Heat Island of Census \nTracts Based off Land Surface Temperature")+
  geom_sf(data = Wallercreek, 
          fill = "NA", 
          color = "black", 
          size = 1)+
  theme_minimal()+
  coord_sf(datum=NA,xlim = mapRange[c(1:2)], ylim = mapRange[c(3:4)])

uhi_plot_waller 
```



```{r, include=FALSE}
tree_count = st_read(dsn = ".", layer = "countingtrees") %>% 
   st_transform(crs = 4326)%>% 
  mutate(tree_intensity = tree_sum/shape_area)

tree_count_only = tree_count %>% 
  dplyr::select(fid, uhi, tree_numbe, tree_sum, shape_area, tree_intensity) %>% 
  as.data.frame() 
```

```{r, include=FALSE}
tree_plot = ggplot(tree_count)+
  geom_sf(aes(fill = tree_intensity))+
  scale_fill_gradient("Simulated Canopy Intensity", low = "lightyellow", high = "darkgreen", breaks=c(0,9.818678e-07),labels=c("Low","High"))+
  labs(x = "", y = "", title = "Simulated Tree Intensity By Census Tract")+
  geom_sf(data = Wallercreek, 
          fill = "NA", 
          color = "black", 
          size = 1)+
  theme_minimal()+
  coord_sf(datum=NA)
tree_plot
```


```{r, include=FALSE}
tree_plot_waller = ggplot(tree_count)+
  geom_sf(aes(fill = tree_intensity))+
  scale_fill_gradient("Simulated Canopy Intensity", low = "lightyellow", high = "darkgreen", breaks=c(0,9.818678e-07),labels=c("Low","High"))+
  labs(x = "", y = "", title = "Simulated Tree Intensity By Census Tract")+
  geom_sf(data = Wallercreek, 
          fill = "NA", 
          color = "black", 
          size = 1)+
  theme_minimal()+
  coord_sf(datum=NA,xlim = mapRange[c(1:2)], ylim = mapRange[c(3:4)])
tree_plot_waller

```

```{r, echo=FALSE, comment=" "}
#uhi_regress = lm(uhi~tree_intensity, data = tree_count_only)
#summary(uhi_regress)

ggplot(tree_count_only)+
  geom_point(aes(x = tree_intensity,y=uhi))+
  theme_classic()+
  labs(title = "Relationship Between Urban Heat Island and Simulated \nTree Canopy by Austin Census Tract", y = "Comparitive Land Surface Temperature Intensity", x = "Simulated Tree Intensity")+
  geom_smooth(method = "lm", aes(x = tree_intensity,y=uhi))+
  geom_text(x = 7.5e-07, y = 0.25, aes(label = "*** R Squared = 0.28"))+
  scale_x_continuous(breaks=c(min(census_social$tree_intensity), max(census_social$tree_intensity)), labels=c("Low","High"))

```


```{r, include=FALSE}
avg_tree = mean(tree_count$tree_intensity)
value_per_tree = 56
tree_value = tree_count %>% 
  mutate(tree_disc=tree_intensity-avg_tree) %>% 
  mutate(tree_disc_num = tree_disc*shape_area) %>% 
  mutate(value_disc = tree_disc_num*value_per_tree) %>% 
  mutate(tree_ben = tree_intensity*value_per_tree)
```


```{r, include=FALSE}
tree_plot_benefit = ggplot(tree_value)+
  geom_sf(aes(fill = tree_ben))+
  scale_fill_gradient("Value",low = "oldlace", high = "deepskyblue4", breaks=c(min(tree_value$tree_ben),max(tree_value$tree_ben)),labels=c("$0","$34,000"))+
  #scale_colour_brewer(palette = "PiYG")+
  labs(x = "", y = "", title = "Tree Value Based on Simulated Tree \nIntensity By Census Tract")+
  geom_sf(data = Wallercreek, 
          fill = "NA", 
          color = "black", 
          size = 1)+
  theme_minimal()+
  coord_sf(datum=NA)
tree_plot_benefit
```


```{r}

tree_plot_value = ggplot(tree_value)+
  geom_sf(aes(fill = value_disc))+
  scale_fill_gradient2("Value Discrepency",low = "firebrick4", mid = "white", high = "deepskyblue4", breaks=c(min(tree_value$value_disc),0,max(tree_value$value_disc)),labels=c("-$9,000","$0","$15,000"))+
  #scale_colour_brewer(palette = "PiYG")+
  labs(x = "", y = "", title = "Tree Value Discrepency Based on Simulated Tree \nIntensity By Census Tract")+
  geom_sf(data = Wallercreek, 
          fill = "NA", 
          color = "black", 
          size = 1)+
  theme_minimal()+
  coord_sf(datum=NA)
tree_plot_value
```

```{r}
croppedcensus = st_read(dsn = ".", layer = "treewallerclipped") %>% 
   st_transform(crs = 4326)
tree_value_waller = croppedcensus %>%
  mutate(tree_intensity = tree_sum/shape_area) %>% 
  mutate(tree_disc=tree_intensity-avg_tree) %>% 
  mutate(tree_disc_num = tree_disc*shape_area) %>% 
  mutate(value_disc = tree_disc_num*value_per_tree)
```

```{r}
tree_plot_waller_value = ggplot(tree_value_waller)+
  geom_sf(aes(fill = value_disc))+
  scale_fill_gradient2("Value Discrepency",low = "firebrick4", mid = "white", high = "deepskyblue4", breaks=c(min(tree_value_waller$value_disc),0,max(tree_value_waller$value_disc)),labels=c("-$550","$0","$400"))+
  #scale_colour_brewer(palette = "PiYG")+
  labs(x = "", y = "", title = "Tree Value Discrepency Based on Simulated Tree \nIntensity By Census Tract")+
  geom_sf(data = Wallercreek, 
          fill = "NA", 
          color = "black", 
          size = 1)+
  theme_minimal()+
  coord_sf(datum=NA)
tree_plot_waller_value
```


