---
title: "AustinLandCover"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
library(sf)
library(leaflet)
library(tmap)
library(spatstat)
library(maptools)
library(sp)
library(raster)
library(beepr)
library(RColorBrewer)
library(stargazer)
```

```{r}
#landcoverNW = st_read(dsn = ".", layer = "AustinEastNW") %>% 
 #  st_transform(crs = 4326)

#hi
landcoverwaller = st_read(dsn = ".", layer = "area_updated")
beep(8)
```

```{r}
ggplot(landcoverwaller)+
  geom_bar(aes(x = FEATURE))+
  theme_classic()
```

```{r}
wlr_area = 2853746.96 #m2

land_sum = landcoverwaller %>% 
  group_by(FEATURE) %>% 
  summarise(sum_area = sum(area_m2_up)) %>% 
  arrange(-sum_area)
land_sum


#beep(6)
#frac_impervous=((sum(land_sum$sum_area)-(18010340+536880+111809.4+60614.13+48861.97+21312.08))/sum(land_sum$sum_area))
#frac_impervous

sum(land_sum$sum_area)
```



```{r}

pavedwaller = landcoverwaller %>% 
filter(FEATURE == "Structure"| FEATURE == "Paved"| FEATURE == "Sidewalk"| FEATURE == "Paved Parking"| FEATURE == "Edge of Paved Road")
#filter(FEATURE == "Remaining Pervious Area")



cover_plot = ggplot(landcoverwaller)+
  geom_sf(aes(fill = FEATURE))+
  #scale_fill_brewer(palette="Set1")+
  labs(x = "", y = "", title = "Land Cover Features")+
  theme_minimal()+
  coord_sf(datum=NA)
  
cover_plot 
beep(1)

```

```{r}

waller3outline = st_read(dsn = ".", layer = "WLR3") %>% 
  st_transform(crs = 4326)

tmap_mode(mode = "view")
tm_basemap("Esri.WorldImagery")+
  tm_shape(waller3outline)+
  tm_borders(col = "black", lwd = 3)+
  tm_legend(title ="Land Cover Fractions")
 
```


```{r}
tree_area = 798105
pervious = 1350527.1270
fields=49878.5374
paved_road= 326481.1118	
paved_parking = 448883.1722
paved = 72726.9741
sidewalk = 51225.1661
patio = 12368.4789
tanks = 3399.8115
structure=490827.4914
unpaved = 10387.4750
open_storage = 5909.6150
open_space = 5631.2594
unpaved_parking = 4539.4437
Uncovered = 3063.4511	
ball_field =91979.9652	
Courtyard=1773.4052	
Median_10 = 1215.1189		
In_ground=51134.6998	
Above_ground=806.5532		
Bridge=474.8890	
alley=	437.1986	
unpaved_road=566.6631
Dock = 135.8640	
Misc=102.5258	

m_wlr_area = sum(land_sum$sum_area)
```

```{r}
Fr_Paved=(1-(Fr_Bldgs+Fr_DecTr+Fr_Grass+Fr_Bsoil+Fr_Water))

Fr_Bldgs= (structure+tanks+Above_ground+open_storage)/wlr_area #This is taken from the sum of all land area coded as structure

Fr_DecTr= tree_area/wlr_area
#This is taken by adding up all the 1by1 m squares that are marked as being tree canopy from the 2010 tree cover dataset. To see the original data look at the wlr_landuse arc project in the wlr_tree_count shapefile 

Fr_Grass=((pervious-(tree_area*2/3))+fields)/wlr_area#This is the remaining pervious area as from the land_sum subtracted by the area of the trees and bare soil

Fr_Bsoil=(Uncovered+unpaved_road+open_space+unpaved_parking+unpaved)/wlr_area

Fr_Water=0 #Taken from landuse code data set 

Fr_Paved+Fr_Bldgs+Fr_DecTr+Fr_Grass+Fr_Bsoil+Fr_Water

grass=pervious-(tree_area*2/3)+fields
```

